name: Render Keep-Alive (5-Minute Ping)
on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 5 minutes (GitHub's minimum interval)
  workflow_dispatch:       # Optional: Manually trigger the job

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping all Render apps
        run: |
          echo "Pinging Render apps to prevent shutdown..."
          curl -s -o /dev/null -w "Portfolio: %{http_code}\n" https://goodluckurom-portfolio-website.onrender.com
          curl -s -o /dev/null -w "E-Commerce Backend: %{http_code}\n" https://goodluckurom-ecommerce-backend.onrender.com
          curl -s -o /dev/null -w "E-Commerce Frontend: %{http_code}\n" https://goodluckurom-ecommerce.onrender.com
          echo "Last ping: $(date)"
